name: on-tag-pushed

on:
  push:
    tags-ignore:
      - 'last-release'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set project name
      run: echo "project=$(echo ${{ github.ref_name }} | sed 's/-[^-]*$//')"
    - name: Set project version
      run: echo "version=$(echo ${{ github.ref_name }} | rev | cut -d "-" -f 1 | rev)"
