name: release

on:
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm ci
      - name: Version
        shell: bash
        # nx affected --target version --push --base=HEAD~ --skipCommit --trackDeps --parallel=false --skipCommitTypes=docs,ci,test
        run: npx nx affected --base=latest-release --target=version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag latest-release
        shell: bash
        run: |
          git tag -f last-release
          git push origin latest-release --force
